### ISSUE TITLE
Math Course todo tracking

### ISSUE THREAD

**Issue by NiloCK** [patched-network/vue-skuilder#23]
This issue is for tracking work specifically belonging to the Math course.

**Comment by NiloCK** [comment]
- [ ] Evaluating Exponent Expressions

eg:

___ = 3^2

4^___ = 64

16 = _^4

**Comment by NiloCK** [comment]
- [ ] Differentiating Numerator / Denominator

A 'do you know the definition of this word' card:

What is the numerator (/denominator) of this fraction? [ 2/4 ] [ ___ ]

**Comment by NiloCK** [comment]
- [ ] Find the Average of a list

Calculate the average:

2, 5, 6, 1, 4

Params:

    number of elements
    'niceness' of numbers (whole-number answers)
    'niceness' of numbers (whole-number vs fraction, decimal, mixed representations, etc)

**Comment by NiloCK** [comment]
- [ ] Metric Conversions

A sequence of views for converting metric units:

eg,

    4 grams = ___ milligrams
    53 kilometers = ___ meters
    0.5 m^2 = ___ cm^2
    5 blorks = ___ centiblorks

**Comment by NiloCK** [comment]
- [ ] Equation Solver

Make an interface/workflow that allows for solving equations. Eg, prenseted with `4x + 3 = 11`, user input `- 3` should result in `4x = 8`, etc.

Equations should be viewable algebraically and visually (balance scales, algebra tiles).

Tasks:
  - [ ] 'Expression' data type for representing, eg, `4x + 3`. Can use mathJax or similar to render
  - [ ] A UI / input device for 'steps' (adding 4, dividing by 6, taking the square root, etc)
  - [ ] A balance scale visualization
  - [ ] An algebra tile visualization

**Comment by NiloCK** [comment]
Closing as stale / out of immediate scope
